services:
  client:
    build:
      context: ./full-hydrix
    ports:
      - 5010:5010
    command: npm run preview -- --host 0.0.0.0 --port 5010

  # serverimage:
  #   build:
  #     context: ./server-save-image
  #   ports:
  #     - 5011:5011
  #   command: node index.js
  #   working_dir: /app

  servercamera:
     build:
       context: ./server-video-systema
     ports:
       - 5012:5012
     command: node src/server.js
     working_dir: /app   
